import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use | Tiny Suitcase',
  description: 'Terms of Use for Tiny Suitcase — the rules and conditions for using our family travel planning service.',
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#faf7f2' }}>
      {/* ── Header ── */}
      <header style={{ padding: '16px 24px', borderBottom: '1px solid rgba(26,39,68,0.1)', backgroundColor: '#ffffff' }}>
        <a
          href="/"
          style={{ color: '#1a2744', fontWeight: 700, fontSize: 14, textDecoration: 'none', fontFamily: 'Inter, sans-serif' }}
        >
          ← Tiny Suitcase
        </a>
      </header>

      {/* ── Content ── */}
      <main style={{ maxWidth: 800, margin: '0 auto', padding: '40px 24px 64px', fontFamily: 'Arial, sans-serif' }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, color: '#000', marginBottom: 8 }}>TERMS OF USE</h1>
        <p style={{ fontSize: 14, color: '#595959', marginBottom: 32 }}>
          <strong>Last updated: May 30, 2026</strong>
        </p>

        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          These Terms of Use govern your use of Tiny Suitcase (&ldquo;the Service&rdquo;), operated by Tiny
          Suitcase (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) at{' '}
          <a href="https://www.trytinysuitcase.com" style={{ color: '#3030F1' }}>
            trytinysuitcase.com
          </a>
          . By using the Service, you agree to these terms.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          1. DESCRIPTION OF SERVICE
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          Tiny Suitcase is a free family travel planning tool. It uses AI (Anthropic&apos;s Claude) to generate
          personalized destination recommendations, day-by-day itineraries, packing lists, dining guides,
          and hotel recommendations based on the trip details you provide. All output is AI-generated and
          intended as a starting point for your planning — not a guarantee of accuracy or availability.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          2. USE OF AI-GENERATED CONTENT
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          Travel recommendations, itineraries, restaurant picks, and hotel suggestions are generated by
          artificial intelligence and may contain errors, outdated information, or inaccuracies. Always
          verify hours, prices, availability, and safety information independently before booking or
          traveling. We make no warranties regarding the accuracy, completeness, or fitness of
          AI-generated content for any purpose.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          3. NO ACCOUNT REQUIRED; LOCAL DATA STORAGE
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          Tiny Suitcase does not require account creation. Trip planning data you enter is stored locally
          in your browser (&ldquo;localStorage&rdquo;) and is not transmitted to or retained on our servers. Trip
          inputs sent to the Claude AI API are processed to generate recommendations and not retained by
          us after the response is delivered.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          4. THIRD-PARTY SERVICES AND LINKS
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          The Service displays links to third-party services including Booking.com, Airbnb, OpenTable,
          and others. These links are provided for your convenience. We are not affiliated with these
          services and are not responsible for their content, availability, or practices. Booking and
          purchasing decisions made through third-party platforms are entirely between you and those
          platforms. We may receive affiliate commissions from some links, which does not affect the
          recommendations you receive.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          5. GOOGLE PLACES API
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          Our Service uses the Google Places API to retrieve hotel property photos. By using our Service,
          you also agree to be bound by{' '}
          <a href="https://policies.google.com/terms" rel="noopener noreferrer" target="_blank" style={{ color: '#3030F1' }}>
            Google&apos;s Terms of Service
          </a>{' '}
          and{' '}
          <a href="https://policies.google.com/privacy" rel="noopener noreferrer" target="_blank" style={{ color: '#3030F1' }}>
            Google&apos;s Privacy Policy
          </a>
          .
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          6. DISCLAIMER OF WARRANTIES
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND,
          EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE
          UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          7. LIMITATION OF LIABILITY
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          TO THE FULLEST EXTENT PERMITTED BY LAW, TINY SUITCASE SHALL NOT BE LIABLE FOR ANY INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF, OR
          INABILITY TO USE, THE SERVICE OR ANY CONTENT PROVIDED THROUGH THE SERVICE. YOUR SOLE REMEDY
          FOR DISSATISFACTION WITH THE SERVICE IS TO STOP USING IT.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          8. INTELLECTUAL PROPERTY
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          The Tiny Suitcase name, logo, and website design are our property. AI-generated travel
          recommendations and itineraries produced for you through the Service may be used for your
          personal, non-commercial travel planning purposes. You may not resell, redistribute, or
          represent AI-generated content as your own commercial product.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          9. ACCEPTABLE USE
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          You agree not to use the Service to: (a) violate any applicable laws; (b) attempt to
          overload, disrupt, or damage the Service; (c) scrape or harvest content from the Service for
          commercial purposes; or (d) use the Service in any way that could harm other users or third
          parties.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          10. CHANGES TO THESE TERMS
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          We may update these Terms of Use from time to time. The updated version will be indicated by
          the &ldquo;Last updated&rdquo; date at the top of this page. Continued use of the Service after any
          changes constitutes acceptance of the revised terms.
        </p>

        <h2 style={{ fontSize: 19, fontWeight: 700, color: '#000', marginTop: 32, marginBottom: 12 }}>
          11. CONTACT US
        </h2>
        <p style={{ fontSize: 14, color: '#595959', lineHeight: 1.7, marginBottom: 24 }}>
          If you have questions about these Terms of Use, please contact us at:{' '}
          <a href="mailto:eric.shiffman@gmail.com" style={{ color: '#3030F1' }}>
            eric.shiffman@gmail.com
          </a>
        </p>
      </main>

      {/* ── Footer ── */}
      <footer style={{ textAlign: 'center', padding: '24px', fontSize: 12, color: '#888', borderTop: '1px solid rgba(26,39,68,0.1)', fontFamily: 'Inter, sans-serif' }}>
        <a href="/" style={{ color: '#888', textDecoration: 'none' }}>Home</a>
        {' · '}
        <a href="/privacy" style={{ color: '#888', textDecoration: 'none' }}>Privacy Policy</a>
        {' · '}
        <a href="/terms" style={{ color: '#888', textDecoration: 'none' }}>Terms of Use</a>
      </footer>
    </div>
  );
}
